# Generated by Django 3.1.3 on 2020-11-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_apis', '0002_reportphoto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportphoto',
            table='report_photo',
        ),
    ]
