# Generated by Django 3.1.3 on 2020-11-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_apis', '0003_auto_20201121_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
