# Generated by Django 3.1.3 on 2020-11-21 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_apis', '0005_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='photo_id',
        ),
        migrations.AddField(
            model_name='reportphoto',
            name='report_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beta_apis.report'),
        ),
    ]
