# Generated by Django 3.1.3 on 2020-11-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_apis', '0007_auto_20201121_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportphoto',
            name='report_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
