# Generated by Django 3.1.3 on 2020-11-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_apis', '0008_auto_20201121_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='reportphoto',
            options={'verbose_name_plural': 'Report Photos'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='report',
            name='user_id',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
